apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrs-pvc-azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi-premium